services:
  - type: web
    name: pixel-positions
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: APP_KEY
      - key: APP_DEBUG
        value: false
